#!/usr/bin/env bash
## Transfer a file to your server.

###	Parameters (4)
###	1. The path to the file to be transferred
###	2. The IP of the server we want to transfer the file to
###	3. The username scp connects with
###	4. The path to the SSH private key (~/.ssh/id_rsa) that scp uses

if [ "$#" -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ "$#" -eq 4 ]
then
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:~/"
fi
