#!/usr/bin/env bash
## Install nginx web server and Redirection.

### Update operating system packages.
sudo apt-get -y update
### Install nginx.
sudo apt-get -y install nginx
### Add permission modify /var/www
sudo chown -R ubuntu /var/www
### Change de defaul content of index.html for nginx.
echo "Hello World" > /var/www/html/index.nginx-debian.html
### The redirection must be a “301 Moved Permanently”.
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/cristhian1107 permanent;/" /etc/nginx/sites-available/default
### Start service nginx.
sudo service nginx restart
