#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd.
while IFS=: read -r f1 f2 f3 f4 f5 f6 f7
do
    echo -n "The user $f1 is part of the $f4 gang, "
    echo -n "lives in $f6 and rides $f7. $f3's place is protected by the passcode $f2, "
    echo "more info about the user here: $f5"
done < "/etc/passwd"
