#!/usr/bin/env bash
# Bash script that groups visitors by IP and HTTP status code, and displays this data from teh Apache log file
awk -F' ' '{ print $1 " " $9 }' apache-access.log | sort | uniq -c | sort -nr
