#!/usr/bin/env bash
# Script that gives you information about the school file.
filename="school"
if [ -e $filename ]
then
	echo "$filename file exists"

	if [ -s ./school ]
	then
		echo "$filename file is not empty"
	else
		echo "$filename file is empty"
	fi

	if [ -f $filename ]
    	then
		echo "$filename is a regular file"
	fi
else
	echo "$filename file does not exist"
fi
