#!/usr/bin/env bash
## Run Nginx as Nginx.
### Change permission.
chmod 777 /etc/nginx/nginx.conf
### Nginx must be listening on all active IPs on port 8080.
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
### Change user
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
### Restart service with nginx user.
pkill -9 apache
sudo -u nginx service nginx restart
