#!/usr/bin/env bash
## Run Nginx as Nginx.
chown nginx:nginx /etc/nginx/nginx.conf
chmod 777 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill -9 apache
sudo -u nginx service nginx start
